### ISSUE TITLE
[Request] Full Size Enclosure  - Front & Back

### ISSUE THREAD

**Issue by JayceeB1** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#1]
Hi.

First thanks for your great work!
I'll be using your project to fit my MKS Gen L & Pi3 :)

But I've got some DC/DC converters & relay to fit in the box, and it looks too small.

So it might be great to make a full size enclosure that uses all the place under the Ender3 - front and back.
Front for mainboards, and back for cable management & other electronics.
Kinda like this control box https://www.thingiverse.com/thing:3072566 , but under the printer.

What do you think about it?

Sorry that I can't contribute in a better way to this project, my design skills are not that good. ^^

**Comment by BladeScraper-Designs** [comment]
I've seen some people mirror the entire case and put it on the backside.  I've not done it myself, but I know it's been done.
