### ISSUE TITLE
Can not open Base Cover Left

### ISSUE THREAD

**Issue by HansGrub3r** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#4]
Hi!

Not sure what's wrong but I can not open Base Cover Left.stl in any software.
Cura crashes the second I import it, Simplify3D tells me it's too big for my printer no matter how big of a printer I tell it I got, 3D Builder tells me the file i broken and Meshmixer says there's a error within the file.

Would really like to print this since I just upgraded my Ender with a MKS Gen v1.4

**Comment by BladeScraper-Designs** [comment]
Seems to have been a corrupt file.  I checked again and it wouldn't load for me either.  I reconverted it to STL and added it here, should be fine now.  Sorry about that.
