### ISSUE TITLE
Pi ang buck Converter 

### ISSUE THREAD

**Issue by dlhazelwood** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#6]
Have you thought about doing a pi and buck converter mount?

**Comment by dlhazelwood** [comment]
Sorry fat fingered the subject.

**Comment by BladeScraper-Designs** [comment]
I'm not sure there'd be enough room for the converter unfortunately.  The Pi takes up most of the space on the right side of the enclosure.  Unless you had something else in mind?

**Comment by dlhazelwood** [comment]
I was thinking on one ofnthe side walls
