### ISSUE TITLE
Support for MKS Rumba+ V1.0

### ISSUE THREAD

**Issue by Bernikolas** [BladeScraper-Designs/Ender-3-All-in-One-Enclosure#8]
Can we have support for MKS Rumba+ V1.0 ? 
Dimensions of the board and specs can be found here:
https://imgur.com/a/xHknI

Thank

**Comment by BladeScraper-Designs** [comment]
Added.  I can't find a CAD model to test with, but the dimensions match.  You'll probably have to face the USB port to the right side of the enclosure, or find a low profile right angle connector for the USB port, as I'm not sure on the clearance for it.

**Comment by Bernikolas** [comment]
Thanks! I will give it a try tonight when I get to my printer!

**Comment by Bernikolas** [comment]
Thanks again for your mod. 
However, either I am do not get something right, or there is a screw hole pillar (do not know the correct terminology apparently! ) missing. 
As I am away from my hardware I tried to align the board design to the case and in both cases (usb port to the left, usb port to the right) one screw hole is missing its pillar.
See please my poor attempts below....
![version_a](https://user-images.githubusercontent.com/22654259/51523856-3acb1b00-1e35-11e9-8b2d-63f11b2c4ee3.jpg)
![version_b](https://user-images.githubusercontent.com/22654259/51523883-47e80a00-1e35-11e9-83da-58236694ee64.jpg)

In the blue circles, are the matched screw holes, in the green one is the missing...

For me this a no issue as I can perfectly mount the board with the 3 holes aligned and the miss-aligned pillars can provide enough support to the board.

Also the exact board name is MKS Rumba**+** V1.0 if you want to update the documentation.

Again thank you for the time you have spent on this excellent design!
